# Generated by Django 5.0.4 on 2024-04-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(max_length=30)),
                ('Salary', models.IntegerField()),
                ('Location', models.CharField(max_length=30)),
                ('Company_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Homes',
        ),
    ]
