# Generated by Django 5.0.4 on 2024-04-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homes', '0002_jobdata_delete_homes'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdata',
            name='CompanY_logo',
            field=models.ImageField(default='exit', upload_to='./Homes'),
            preserve_default=False,
        ),
    ]
