# Generated by Django 5.0.4 on 2024-04-28 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homes', '0003_jobdata_company_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobdata',
            name='CompanY_logo',
        ),
        migrations.AddField(
            model_name='jobdata',
            name='Company_logo',
            field=models.ImageField(default='NONE', upload_to='./Homes/'),
        ),
    ]
