# Generated by Django 5.0.4 on 2024-04-28 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Homes', '0004_remove_jobdata_company_logo_jobdata_company_logo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobData',
            new_name='Job',
        ),
    ]
