# Generated by Django 5.0.4 on 2024-04-29 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homes', '0005_rename_jobdata_job'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='Salary',
        ),
        migrations.AddField(
            model_name='job',
            name='From_Salary',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='job',
            name='Job_type',
            field=models.CharField(default='Full Time', max_length=50),
        ),
        migrations.AddField(
            model_name='job',
            name='To_Salary',
            field=models.IntegerField(default=0),
        ),
    ]
