# Generated by Django 5.0.4 on 2024-05-11 16:03

import autoslug.fields
import django.db.models.deletion
import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homes', '0006_remove_job_salary_job_from_salary_job_job_type_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='job',
            managers=[
                ('cm', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=20)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='category_name', unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Homes.job')),
            ],
        ),
    ]
