# Generated by Django 5.0.4 on 2024-05-29 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homes', '0008_remove_category_category_job_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Company_description',
            field=models.TextField(default='CD2', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='Job_description',
            field=models.TextField(default='JD', null=True),
        ),
    ]
