# Generated by Django 5.0.4 on 2024-06-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homes', '0009_job_company_description_job_job_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Company_description',
            field=models.TextField(default='Company Description', null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='Job_description',
            field=models.TextField(default='Job Description', null=True),
        ),
    ]
