# Generated by Django 5.0.4 on 2024-06-02 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homes', '0011_alter_job_from_salary_alter_job_to_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='Job_status',
            field=models.BooleanField(default=False),
        ),
    ]
