# Generated by Django 5.0.4 on 2024-06-07 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homes', '0013_job_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='files',
            field=models.FileField(default='NONE', upload_to='./Homes/'),
        ),
    ]
